name: Validate Python e2e
on:
  push: # define action

jobs: # define the workflow
  test-windows:
    runs-on: windows-latest # select os
    steps:      #set the steps
      - uses: actions/checkout@v1       
      - uses: actions/setup-python@v2 #to use python 
        with:
          python-version: '3.8' # select python version 3.8
      - name: Python unit tests # integret library for test
        run:  python3 -m unittest test_guess_the_number.py # run the test.
